/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libarary_management_syste.view;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libarary_management_syste.controller.BookController;
import libarary_management_syste.dto.BookDto;

/**
 *
 * @author LENOVO
 */
public class BookView extends javax.swing.JFrame {

    private BookController bookController;

    /**
     * Creates new form BookView
     */
    public BookView() throws Exception {
        bookController = new BookController();
        initComponents();
        LoadBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booklbl = new javax.swing.JLabel();
        bookidlbl = new javax.swing.JLabel();
        booidtxt = new javax.swing.JTextField();
        booknamelbl = new javax.swing.JLabel();
        booknametxt = new javax.swing.JTextField();
        itemidlbl = new javax.swing.JLabel();
        itemidtxt = new javax.swing.JTextField();
        isbnlbl = new javax.swing.JLabel();
        isbntxt = new javax.swing.JTextField();
        authorlbl = new javax.swing.JLabel();
        authortxt = new javax.swing.JTextField();
        savebtt = new javax.swing.JButton();
        upadatebtt = new javax.swing.JButton();
        deletebtt = new javax.swing.JButton();
        serchbtt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booktbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booklbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booklbl.setText("BOOK FORM");
        getContentPane().add(booklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 490, -1));

        bookidlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookidlbl.setText("BOOK ID");
        getContentPane().add(bookidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 94, -1));
        getContentPane().add(booidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 186, -1));

        booknamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booknamelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libarary_management_syste/images/HOW-DO-YOU-MANAGE-A-LIBRARY-min.png"))); // NOI18N
        booknamelbl.setText("BOOK NAME");
        getContentPane().add(booknamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 410));
        getContentPane().add(booknametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 186, -1));

        itemidlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemidlbl.setText("ITEM ID");
        getContentPane().add(itemidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 73, -1));
        getContentPane().add(itemidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 186, -1));

        isbnlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isbnlbl.setText("ISBN");
        getContentPane().add(isbnlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 68, -1));
        getContentPane().add(isbntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 186, -1));

        authorlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorlbl.setText("AUTHOR");
        getContentPane().add(authorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 82, -1));
        getContentPane().add(authortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 186, -1));

        savebtt.setText("SAVE");
        savebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebttActionPerformed(evt);
            }
        });
        getContentPane().add(savebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        upadatebtt.setText("UPDATE");
        upadatebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upadatebttActionPerformed(evt);
            }
        });
        getContentPane().add(upadatebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        deletebtt.setText("DELETE");
        deletebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebttActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        serchbtt.setText("SERCH");
        serchbtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchbttActionPerformed(evt);
            }
        });
        getContentPane().add(serchbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        booktbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(booktbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 80, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebttActionPerformed
        SaveBook();
    }//GEN-LAST:event_savebttActionPerformed

    private void upadatebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upadatebttActionPerformed
        UpdateBook();
    }//GEN-LAST:event_upadatebttActionPerformed

    private void deletebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebttActionPerformed
        DeleteBook();
    }//GEN-LAST:event_deletebttActionPerformed

    private void serchbttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchbttActionPerformed
        SerchBook();
    }//GEN-LAST:event_serchbttActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       Exit();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorlbl;
    private javax.swing.JTextField authortxt;
    private javax.swing.JTextField booidtxt;
    private javax.swing.JLabel bookidlbl;
    private javax.swing.JLabel booklbl;
    private javax.swing.JLabel booknamelbl;
    private javax.swing.JTextField booknametxt;
    private javax.swing.JTable booktbl;
    private javax.swing.JButton deletebtt;
    private javax.swing.JButton exit;
    private javax.swing.JLabel isbnlbl;
    private javax.swing.JTextField isbntxt;
    private javax.swing.JLabel itemidlbl;
    private javax.swing.JTextField itemidtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savebtt;
    private javax.swing.JButton serchbtt;
    private javax.swing.JButton upadatebtt;
    // End of variables declaration//GEN-END:variables

    
    
    public void Exit(){
        new MainView().setVisible(true);
    }
    private void SaveBook() {
        BookDto dto = new BookDto();
        dto.setBookId(Integer.valueOf(booidtxt.getText()));
        dto.setName(booknametxt.getText());
        dto.setIsbn(isbntxt.getText());
        dto.setAuthor(authortxt.getText());
        dto.setItemId(Integer.valueOf(itemidtxt.getText()));

        try {
            String result = bookController.saveBook(dto);
            JOptionPane.showMessageDialog(this, result);
            Clear();
            LoadBook();
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void UpdateBook() {
        try {
            BookDto dto = new BookDto();
            dto.setBookId(Integer.valueOf(booidtxt.getText()));
            dto.setName(booknametxt.getText());
            dto.setIsbn(isbntxt.getText());
            dto.setAuthor(authortxt.getText());
            dto.setItemId(Integer.valueOf(itemidtxt.getText()));

            String resp = bookController.UpdateBook(dto);
            JOptionPane.showMessageDialog(this, resp);
            Clear();
            LoadBook();
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void DeleteBook() {
        try {
            Integer Id = Integer.valueOf(booidtxt.getText());
            String resp = bookController.DeleteBook(Id);
            JOptionPane.showMessageDialog(this, resp);
            Clear();
            LoadBook();

        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void SerchBook() {
        Integer Id = Integer.valueOf(booktbl.getValueAt(booktbl.getSelectedRow(), 0).toString());
        try {
            BookDto dto = bookController.serchBook(Id);
            if (dto != null) {
                booidtxt.setText(String.valueOf(dto.getBookId()));
                booknametxt.setText(dto.getName());
                isbntxt.setText(dto.getIsbn());
                authortxt.setText(dto.getAuthor());
                itemidtxt.setText(String.valueOf(dto.getItemId()));

            } else {
                JOptionPane.showMessageDialog(this, "Book Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void LoadBook() {
        try {
            String columns[] = {"BOOK ID", "BOOK NAME", "ISBN", "AUTHOR", "ITEM ID"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            booktbl.setModel(dtm);
            List<BookDto> bookdtos = bookController.getAllBook();
            for (BookDto bookdto : bookdtos) {
                Object[] rowData = {bookdto.getBookId(), bookdto.getName(), bookdto.getIsbn(), bookdto.getAuthor(), bookdto.getItemId()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }

    private void Clear() {
        booidtxt.setText("");
        booknametxt.setText("");
        isbntxt.setText("");
        authortxt.setText("");
        itemidtxt.setText("");
       
    }

}
