/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libarary_management_syste.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libarary_management_syste.controller.DvdController;
import libarary_management_syste.dto.BookDto;
import libarary_management_syste.dto.DvdDto;

/**
 *
 * @author LENOVO
 */
public class DvdView extends javax.swing.JFrame {

    private DvdController dvdController;

    /**
     * Creates new form DvdView
     */
    public DvdView() throws Exception {
        dvdController = new DvdController();
        initComponents();
        loadDvD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dvdidlbl = new javax.swing.JLabel();
        dvdidtxt = new javax.swing.JTextField();
        dvdnamelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diretorttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        durationtxt = new javax.swing.JTextField();
        itemidtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dvdtbl = new javax.swing.JTable();
        savebtt = new javax.swing.JButton();
        updatebtt = new javax.swing.JButton();
        deletebtt = new javax.swing.JButton();
        serchbtt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitbtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dvdidlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dvdidlbl.setText("DVD ID ");
        getContentPane().add(dvdidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 89, -1));
        getContentPane().add(dvdidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 242, -1));

        dvdnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dvdnamelbl.setText("DVD NAME ");
        getContentPane().add(dvdnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 89, -1));
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 242, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DIRECTOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 99, -1));
        getContentPane().add(diretorttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 242, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libarary_management_syste/images/HOW-DO-YOU-MANAGE-A-LIBRARY-min.png"))); // NOI18N
        jLabel4.setText("DURATION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));
        getContentPane().add(durationtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 242, -1));
        getContentPane().add(itemidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 242, -1));

        dvdtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dvdtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

        savebtt.setText("SAVE");
        savebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebttActionPerformed(evt);
            }
        });
        getContentPane().add(savebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, -1, -1));

        updatebtt.setText("UPDATE");
        updatebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebttActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        deletebtt.setText("DELETE");
        deletebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebttActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, -1, -1));

        serchbtt.setText("SERCH");
        serchbtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchbttActionPerformed(evt);
            }
        });
        getContentPane().add(serchbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEM ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 90, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DVD FORM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 280, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Duration");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 110, 20));

        exitbtt.setText("EXIT");
        exitbtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbttActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebttActionPerformed
        dvdsave();
    }//GEN-LAST:event_savebttActionPerformed

    private void updatebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebttActionPerformed
        dvdupdate();
    }//GEN-LAST:event_updatebttActionPerformed

    private void deletebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebttActionPerformed
        dvddelete();
    }//GEN-LAST:event_deletebttActionPerformed

    private void serchbttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchbttActionPerformed
        dvddserch();
    }//GEN-LAST:event_serchbttActionPerformed

    private void exitbttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbttActionPerformed
        exit();
    }//GEN-LAST:event_exitbttActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DvdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DvdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DvdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DvdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DvdView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtt;
    private javax.swing.JTextField diretorttxt;
    private javax.swing.JTextField durationtxt;
    private javax.swing.JLabel dvdidlbl;
    private javax.swing.JTextField dvdidtxt;
    private javax.swing.JLabel dvdnamelbl;
    private javax.swing.JTable dvdtbl;
    private javax.swing.JButton exitbtt;
    private javax.swing.JTextField itemidtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton savebtt;
    private javax.swing.JButton serchbtt;
    private javax.swing.JButton updatebtt;
    // End of variables declaration//GEN-END:variables

    public void exit(){
        new MainView().setVisible(true);
    }
    
    
    
    private void dvdsave() {
        DvdDto dto = new DvdDto();
        dto.setDvdId(Integer.valueOf(dvdidtxt.getText()));
        dto.setDvdname(nametxt.getText());
        dto.setDirector(diretorttxt.getText());
        dto.setDuration(durationtxt.getText());
        dto.setItemId(Integer.valueOf(itemidtxt.getText()));
        try {
            String result = dvdController.saveDVD(dto);
            JOptionPane.showMessageDialog(this, result);
            loadDvD();
            clearDvd();

        } catch (Exception e) {
            Logger.getLogger(DvdView.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void dvdupdate() {
        DvdDto dto = new DvdDto();
        dto.setDvdId(Integer.valueOf(dvdidtxt.getText()));
        dto.setDvdname(nametxt.getText());
        dto.setDirector(diretorttxt.getText());
        dto.setDuration(durationtxt.getText());
        dto.setItemId(Integer.valueOf(itemidtxt.getText()));
        try {
            String result = dvdController.UpdateDvd(dto);
            JOptionPane.showMessageDialog(this, result);
            loadDvD();
            clearDvd();

        } catch (Exception e) {
            Logger.getLogger(DvdView.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void dvddelete() {
       try {
            Integer Id = Integer.valueOf(dvdidtxt.getText());
            String resp = dvdController.DeleteDvd(Id);
            JOptionPane.showMessageDialog(this, resp);
            loadDvD();
            clearDvd();

        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void dvddserch() {
        Integer Id = Integer.valueOf(dvdtbl.getValueAt(dvdtbl.getSelectedRow(), 0).toString());
        try {
            DvdDto dto = dvdController.serchDvd(Id);
            if (dto != null) {
                dvdidtxt.setText(String.valueOf(dto.getDvdId()));
                nametxt.setText(dto.getDvdname());
                diretorttxt.setText(dto.getDirector());
                durationtxt.setText(dto.getDuration());
                itemidtxt.setText(String.valueOf(dto.getItemId()));

            } else {
                JOptionPane.showMessageDialog(this, "DVD Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void loadDvD() {
        try {
            String columns[] = {"DVD ID", "DVD NAME", "DIRECTOR", "DURATION", "ITEM ID"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            dvdtbl.setModel(dtm);
            List<DvdDto> dvddtos = dvdController.getAllDvd();
            for (DvdDto dvddto : dvddtos) {
                Object[] rowData = {dvddto.getDvdId(), dvddto.getDvdname(), dvddto.getDirector(), dvddto.getDuration(), dvddto.getItemId()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(DvdView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }

    private void clearDvd() {
        dvdidtxt.setText("");
        nametxt.setText("");
        diretorttxt.setText("");
        durationtxt.setText("");
        itemidtxt.setText("");
    }

}
