/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libarary_management_syste.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libarary_management_syste.controller.ItemController;
import libarary_management_syste.dto.BookDto;
import libarary_management_syste.dto.ItemDto;

/**
 *
 * @author LENOVO
 */
public class ItemView extends javax.swing.JFrame {

    private ItemController itemController;

    public ItemView() throws Exception {
        itemController = new ItemController();
        initComponents();
        LoadItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        itemidtxt = new javax.swing.JTextField();
        itemnametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        savebtt = new javax.swing.JButton();
        updatebtt = new javax.swing.JButton();
        deletebtt = new javax.swing.JButton();
        serchbtt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itmtbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        avilabilitytxt = new javax.swing.JComboBox<>();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libarary_management_syste/images/all pages background.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libarary_management_syste/images/HOW-DO-YOU-DESIGN-A-LIBRARY-MANAGEMENT-SYSTEM-min-768x768.png"))); // NOI18N
        jLabel1.setText("ITEM ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));
        getContentPane().add(itemidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 225, -1));
        getContentPane().add(itemnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 225, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ITEM NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 74, -1));

        savebtt.setText("SAVE");
        savebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebttActionPerformed(evt);
            }
        });
        getContentPane().add(savebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 100, -1));

        updatebtt.setText("UPDATE");
        updatebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebttActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 560, 100, -1));

        deletebtt.setText("DELETE");
        deletebtt.setToolTipText("");
        deletebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebttActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 100, -1));

        serchbtt.setText("SERCH");
        serchbtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchbttActionPerformed(evt);
            }
        });
        getContentPane().add(serchbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 660, 100, -1));

        itmtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(itmtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 410, -1));

        jLabel5.setText("AVILABILITY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ITEM ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 80, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ITEM FORM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 310, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 510, 90, -1));

        avilabilitytxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Return Item", "Borrow Item" }));
        getContentPane().add(avilabilitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebttActionPerformed
        SaveItem();
    }//GEN-LAST:event_savebttActionPerformed

    private void updatebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebttActionPerformed
        Updateitem();
    }//GEN-LAST:event_updatebttActionPerformed

    private void deletebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebttActionPerformed
        DeleteItem();
    }//GEN-LAST:event_deletebttActionPerformed

    private void serchbttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchbttActionPerformed
        SerchItem();
    }//GEN-LAST:event_serchbttActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        Exit();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> avilabilitytxt;
    private javax.swing.JButton deletebtt;
    private javax.swing.JButton exit;
    private javax.swing.JTextField itemidtxt;
    private javax.swing.JTextField itemnametxt;
    private javax.swing.JTable itmtbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savebtt;
    private javax.swing.JButton serchbtt;
    private javax.swing.JButton updatebtt;
    // End of variables declaration//GEN-END:variables

    public void Exit(){
        new MainView().setVisible(true);
    }
    
    
    private void SaveItem() {
        ItemDto dto = new ItemDto();
        dto.setItemId(Integer.valueOf(itemidtxt.getText()));
        dto.setItemName(itemnametxt.getText());
        dto.setAvilibilty((String) avilabilitytxt.getSelectedItem());

        try {
            String result = itemController.saveItem(dto);
            JOptionPane.showMessageDialog(this, result);
            clearItem();
            LoadItem();
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void Updateitem() {
        try {
            ItemDto dto = new ItemDto();
            dto.setItemId(Integer.valueOf(itemidtxt.getText()));
            dto.setItemName(itemnametxt.getText());
            dto.setAvilibilty((String) avilabilitytxt.getSelectedItem());

            String resp = itemController.updateItem(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearItem();
            LoadItem();
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void DeleteItem() {
        try {
            Integer Id = Integer.valueOf(itemidtxt.getText());
            String resp = itemController.deleteItem(Id);
            JOptionPane.showMessageDialog(this, resp);
            clearItem();
            LoadItem();
                 
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void SerchItem() {
        Integer Id = Integer.valueOf(itmtbl.getValueAt(itmtbl.getSelectedRow(), 0).toString());
        try {
            ItemDto dto = itemController.serchItem(Id);
            if (dto != null) {
                itemidtxt.setText(String.valueOf(dto.getItemId()));
                itemnametxt.setText(dto.getItemName());
                avilabilitytxt.setSelectedItem(dto.getAvilibilty());
                
            } else {
                JOptionPane.showMessageDialog(this, "Item Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void LoadItem() {
        try {
            String columns[] = {"ITEM ID", "NAME", "AVILABILITY"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            itmtbl.setModel(dtm);
            List<ItemDto> itemdtos = itemController.getAllItem();
            for (ItemDto itemdto : itemdtos) {
                Object[] rowData = {itemdto.getItemId(), itemdto.getItemName(), itemdto.getAvilibilty()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(BookView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }

    private void clearItem() {
        itemidtxt.setText("");
        itemnametxt.setText("");
      
    }
}
